- name: Installing docker apt dependencies
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    state: latest
    update_cache: true
 
- name: get apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
     
- name: add apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: install docker
  apt:
    name: ['docker-ce','docker-ce-cli','containerd.io']
    state: latest
    update_cache: true 
